spring.application.name: sms-service
server.port: 8080

eureka.instance.prefer-ip-address: true
eureka.instance.instance-id: ${spring.cloud.client.ip-address}:${server.port}

eureka.client:
        register-with-eureka: true
        fetch-registry: true
        registry-fetch-interval-seconds: 5
        service-url:
            defaultZone: http://localhost:1111/eureka
